/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/105107ba-58da-4d69-8f4c-3ed5e3049f03 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float sensorFumaca;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

/* ao abrir o arduino cloud, definir um dispositivo,
ao criar dispositivo sera gerada uma chave salva em um pdf,
usar essa chave como valor de SECRET_DEVICE_KEY em arduino_secrets.h
e sketch.json .
crie uma varivel que vem os dados gerados desse dispositivo
sera gerado um sketch com os 3 arquivos aqui contidos
que pode ser editado com o codigo desejado
é recomendado baixar o arduino cloud agent e com ele ligado
colocar o código no aparelho(esp32) direto da ide da cloud
no browser/app (nesse ambiente as variaveis de ambiente
e as bibliotecas sao mais estaveis e faceis de configurar)
*/

#include "arduino_secrets.h"
#include "thingProperties.h"
#define MQ2_PIN 32

void setup() {
  // Initialize serial and wait for port to open:

  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  Serial.begin(9600);
  analogReadResolution(10);
  Serial.println("Sensor MQ-2 Inicializado!");
  pinMode(MQ2_PIN, INPUT);
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();
}

void loop() {

    
  ArduinoCloud.update();

  sensorFumaca = analogRead(MQ2_PIN);
  Serial.print("Gas Value: ");
  Serial.println(sensorFumaca);
  delay(1000);
  

}